// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgm_GfdX988B7RpUjXHgUmdTbEQUzIq-U',
    appId: '1:493763535929:web:cfd6d0978bb16187f4d9e8',
    messagingSenderId: '493763535929',
    projectId: 'flash-1-d4d68',
    authDomain: 'flash-1-d4d68.firebaseapp.com',
    storageBucket: 'flash-1-d4d68.appspot.com',
    measurementId: 'G-C0E341QL4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_42k70zEzE1QJJy57Dsi95NUcs1cqLv8',
    appId: '1:493763535929:android:8da314917b5cbe79f4d9e8',
    messagingSenderId: '493763535929',
    projectId: 'flash-1-d4d68',
    storageBucket: 'flash-1-d4d68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQpksdtl3P7oAiJOC_p7c_Cv5eDNk9Hs',
    appId: '1:493763535929:ios:55f20cf4389e9267f4d9e8',
    messagingSenderId: '493763535929',
    projectId: 'flash-1-d4d68',
    storageBucket: 'flash-1-d4d68.appspot.com',
    iosClientId: '493763535929-un1441svadvv83ocg9khniui7vt6r88d.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQQpksdtl3P7oAiJOC_p7c_Cv5eDNk9Hs',
    appId: '1:493763535929:ios:762a2ab13e0ea608f4d9e8',
    messagingSenderId: '493763535929',
    projectId: 'flash-1-d4d68',
    storageBucket: 'flash-1-d4d68.appspot.com',
    iosClientId: '493763535929-s3i9qog56sp7d4o9p7dnlqnbgbvbotp0.apps.googleusercontent.com',
    iosBundleId: 'co.appbrewery.flash1',
  );
}
